### PR TITLE
fix issue #1206 #1205 Abnormality of  and attributes

### PR DESCRIPTION
**Pull request by Alanscut**
## Changes 
* The value of the `protection` attribute is not stored after reading the file.
* Fix for issue #1206 and #1205 .

### CODE REVIEW

**Comment by Siemienik** [comment]
What will happen when both, protection and alligment are set?

**Comment by Alanscut** [comment]
Thank you @Siemienik When reading the file, the value of `protection` will be assigned to` alignment`. When writing the file again, `protection` and` alignment` will be set to the default values:).

https://github.com/exceljs/exceljs/pull/1210/files#diff-ad67969c947ed782604ac1cac3c62efaR112

## Wrong
```javascript
{
  numFmtId: 0,
  fontId: 0,
  fillId: 2,
  borderId: 4,
  xfId: 0,
  alignment: { locked: false, hidden: false }
}
```

## Correct
```javascript
{
  numFmtId: 0,
  fontId: 0,
  fillId: 2,
  borderId: 4,
  xfId: 0,
  alignment: { horizontal: 'center', vertical: 'middle', wrapText: true },
  protection: { locked: false, hidden: false }
}
```

**Comment by Siemienik** [comment]
so, it's a WIP, isn't it?

**Comment by Alanscut** [comment]
> so, it's a WIP, isn't it?

@Siemienik sorry for my misleading comment, it's not a WIP, I have updated the last comment, please review it again.

**Pull request merged**
