### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by Hesamp**
https://github.com/exceljs/exceljs/issues/1517

### CODE REVIEW

**Comment by alubbe** [comment]
@Siemienik could you help review this?

**Comment by Siemienik** [comment]
@alubbe really willingly. I have to check it on localhost by creating some sample.
I will have some time at weekend

---
If want you support my OSS/ExcelJS activity #1500

**Comment by sdg9670** [comment]
TS2322: Type '{ header: string; key: string; width: number; }[]' is not assignable to type 'Column[]'.
  Type '{ header: string; key: string; width: number; }' is missing the following properties from type 'Column': outlineLevel, hidden, style, values, and 11 more.

216   ws1.columns = columns;

**Review by Siemienik — APPROVED** [review]
LGTM

**Comment by Hesamp** [comment]
Hi 
I think a new release should be created for this pull request, because version 4.2.0 causes a compilation error in the typescript projects 
image

**Pull request merged**
