### PR TITLE
fix issue #1045 horizontalCentered & verticalCentered in page not working

### PR DESCRIPTION
**Pull request by Alanscut**
### Changes 
1. This PR solves the problem that horizontalCentered & verticalCentered is not working.

2. Fix for #1045

### CODE REVIEW

**Comment by Siemienik** [comment]
@Alanscut thanks for that PR, it's a bit of great work here:) 
Could I ask you to write at least one test which checks this logic? (for example, write and read file + asserts for these properties).

**Comment by Alanscut** [comment]
hi @Siemienik 
Thank you very much for your comment.
See https://github.com/exceljs/exceljs/blob/master/spec/unit/xlsx/xform/sheet/print-options-xform.spec.js#L23

**Comment by Siemienik** [comment]
hmm.. so how the tests work ok before and now after source code was changed? Are both versions correct?

**Comment by Alanscut** [comment]
@Siemienik Having researched the unit test, I found I have misunderstood it. Actually the testcases for it lies in file `worksheet-xform.spec.js`, property `horizontalCentered` are not tested before, so I have add the test case and fixed issue #1079 also.
https://github.com/exceljs/exceljs/blob/9054c3240ea4f5fa70720bfedf14b0c9da751e71/spec/unit/xlsx/xform/sheet/worksheet-xform.spec.js#L53-L70

**Comment by Siemienik** [comment]
great :)

**Pull request merged**
