### PR TITLE
docs: add links to top with jump2header

### PR DESCRIPTION
**Pull request by strdr4605**
## Summary

Links back to Table of contents helps to navigate in the docs.

See [demo](https://github.com/strdr4605/exceljs/blob/jump2header/README.md#importing).

### CODE REVIEW

**Comment by alubbe** [comment]
Please merge the current master into your branch

**Comment by Siemienik** [comment]
@strdr4605 thank you for this improvement :)
Could you (or any) perform the same thing for `README_zh.md`?

**Comment by Alanscut** [comment]
hey @Siemienik, @alubbe  , links now could back to table of contents, but the anchor of the contents failed, should we revert this PR or just fix it? and do you think this logo ⬆ looks too dazzling a bit weired? 😳

**Comment by strdr4605** [comment]
The problem is with https://github.com/exceljs/exceljs/pull/1215/commits/f65592e6dd5b1a1a1ef61c0c6cba29111a35b40e . Without space, everything should work ok. Should revert this PR and change.

> and do you think this logo ⬆ looks too dazzling a bit weired?

There are other icons available also it is possible to change the position of the link.
Check [jump2header#api](https://github.com/strdr4605/jump2header#api).

**Comment by alubbe** [comment]
I think that's github's default - not sure if they support a slimmer arrow
@strdr4605 could you open a PR reverting the change with the spaces?

**Pull request merged**
