### PR TITLE
Modify code causes rich text to be lost

### PR DESCRIPTION
**Pull request by zhangyu836**

### CODE REVIEW

**Comment by guyonroche** [comment]
@zhangyu836 ok to close these other PRs?

- https://github.com/exceljs/exceljs/pull/929
- https://github.com/exceljs/exceljs/pull/973
- https://github.com/exceljs/exceljs/pull/974

**Comment by janbarta** [comment]
Was this actually merged in any PR?

**Comment by guyonroche** [comment]
@zhangyu836 I see you have closed all of the PRs including this one. I'm just trying to understand the intention - by the looks of the changes, its adding formula to Hyperlink values. What would be the use case for this - given that only the display text can be the result of the formula not the actual hyperlink itself?

**Comment by zhangyu836** [comment]
To pass spec\integration\workbook-xlsx-reader.spec.js test.

**Pull request closed without merging**
