### PR TITLE
Feat configure headers and footers

### PR DESCRIPTION
**Pull request by autukill**
Add new features to configure headers and footers.
Not support add image to headers and footers.
Maybe readme.md needs you to re-edit, my English is not good.

### CODE REVIEW

**Comment by alubbe** [comment]
Thanks for your PR! Could you please add some tests for this new feature?

**Comment by autukill** [comment]
Yes, I am working on it.

**Comment by autukill** [comment]
> Thanks for your PR! Could you please add some tests for this new feature?

tests has been added

**Comment by joyacv2** [comment]
Hi Autukill, Guyon!!!!

Thank you very much to both!!!!!!! Excellent!!!!!

I create this one:
https://github.com/exceljs/exceljs/issues/931

and I see that this one maybe is related. I want to know if you have an expected date to release the image feature for header and footer. Thank you very much!!!!!!!!!

**Comment by autukill** [comment]
> Hi Autukill, Guyon!!!!
> 
> Thank you very much to both!!!!!!! Excellent!!!!!
> 
> I create this one:
> #931
> 
> and I see that this one maybe is related. I want to know if you have an expected date to release the image feature for header and footer. Thank you very much!!!!!!!!!

No plan, maybe you can add this feature

**Pull request merged**
