### PR TITLE
Increase resilience to generating large workbooks

### PR DESCRIPTION
**Pull request by hfhchan-plb**
## Summary

Updates the xml-stream.js to generate a single string instead of multiple strings for each attribute or record of attributes.

Closes: #2303

### CODE REVIEW

**Comment by hfhchan-plb** [comment]
@zurmokeeper I renamed the branch on my local repo and GitHub automatically closed https://github.com/exceljs/exceljs/pull/2319.

**Comment by zurmokeeper** [comment]
@hfhchan-plb Could you please move [over here](https://github.com/zurmokeeper/excelize)? I'd be happy to merge this feature.

**Comment by hfhchan-plb** [comment]
@zurmokeeper I don't mind if you wish to cherry pick to your fork, with or without accreditation.

We are currently using our own fork for excel generation which is tracking upstream, so we are unlikely to move to a fork unless there is a good guarantee of maintainability, or a large technical benefit (i.e. completely rewritten in TypeScript, getting rid of old dependencies, etc).

**Comment by Siemienik** [comment]
Sorry for some inconvenience, now I'm able to resume active development - more info would be found in a topic about next release v4.4.0: #2352

**Review by Siemienik — APPROVED** [review]
Good stuff, Thank you @hfhchan-plb

**Pull request merged**
