### PR TITLE
fix: Fix xlsx.writeFile() not catching error when error occurs

### PR DESCRIPTION
**Pull request by zurmokeeper**
## Summary
When `await workbook.xlsx.writeFile(filename).`
was reported, but the error was not caught by try catch, after modifying the source code, it can now be caught

## Test plan
```
try {
    const imageId2 = workbook.addImage({
        buffer: fs.readFileSync('path/to.image.png'),
        extension: 'png',
      });
    await workbook.xlsx.writeFile(filename);
} catch (error) {
    console.log(error)
}
```

### CODE REVIEW

**Review by Siemienik — COMMENTED** [review]
Good catch, looks good for me, but test case is required before merge

**Comment by zurmokeeper** [comment]
> Good catch, looks good for me, but test case is required before merge

Great, I will add the test cases later

**Comment by zurmokeeper** [comment]
@Siemienik Additional test cases have been added

**Review by naorpeled — APPROVED** [review]

**Review by Siemienik — APPROVED** [review]
LGTM, thanks

**Pull request merged**
