### PR TITLE
Only keep at most 31 characters for sheetname

### PR DESCRIPTION
**Pull request by kaleo211**
Addressing [Issue 398](https://github.com/exceljs/exceljs/issues/398).

### CODE REVIEW

**Comment by alubbe** [comment]
Could you please add 2 tests for this:
1. a 31 character name is unchanged
2. a 32 character name is truncated

**Comment by alubbe** [comment]
@guyonroche I think we could print a warning when this happens, or maybe even throw an error, asking the user of the library to only submit short names. What do you think?

**Comment by Siemienik** [comment]
> Could you please add 2 tests for this:
> 
> 1. a 31 character name is unchanged
> 2. a 32 character name is truncated
 
3. two names with more characters than 31, where first 31  characters are equals

eq.
```
ThisIsAnExampleNameWith31Chars_A
ThisIsAnExampleNameWith31Chars_B
```

4. similar but with first letter different:
```
```
A_ThisIsAnExampleNameWith31Chars
B_ThisIsAnExampleNameWith31Chars
```

Because as far as I know, names can't be equals

**Comment by kaleo211** [comment]
> A_ThisIsAnExampleNameWith32Chars

Thank you. I broke down those tests, hope this also works.

**Comment by guyonroche** [comment]
@alubbe 
> @guyonroche I think we could print a warning when this happens, or maybe even throw an error, asking the user of the library to only submit short names. What do you think?
I don't think throwing an error is necessary - but something like a console warning would be appropriate.
This looks good - will merge soon

**Comment by lirantal** [comment]
@guyonroche just chiming in here after I discovered now that this broke some things for me. In the future, I would consider changes like this one as a breaking change. The problem it introduced is that because it is truncating to 31 characters there is now increased potential for duplicate names which will trigger an error thrown.

Regardless, keep up the great work on this library 👏

**Pull request merged**
