### PR TITLE
bug fix can not read property date1904 of undefined

### PR DESCRIPTION
**Pull request by yganatra1**
## Summary

**Issue**: 
ExcelJs.stream.xlsx.WorkbookReader reading with styles: cache option was giving 
**Cannot read property 'date1904' of undefined**

**Reproduce with this code**
```
const workbookReader = new excel.stream.xlsx.WorkbookReader(fileReadStream, { worksheets: 'emit', styles: 'cache', sharedStrings: 'cache', hyperlinks: 'ignore', entries: 'ignore' });
    workbookReader.read();
    workbookReader.on('worksheet', worksheet => { 
         worksheet.on('row', (row) => {...}
     }
```

Above code will throw an error when `DD/MM/YYYY` format date is given in the excel
e.g: 20/06/2020

I found that in `lib/stream/xlsx/worksheet-reader.js` we are using it but not checking for the undefined model case.

### CODE REVIEW

**Review by Alanscut — APPROVED** [review]

**Comment by Siemienik** [comment]
LGFM, but it's required to cover each detected (and fixed) bug by test. Could I ask you to write at least one?

**Review by Siemienik — CHANGES_REQUESTED** [review]
Looks good for me, thanks

I have only one request - it's required to cover each detected (and fixed) bug by a test. Could I ask you to write at least one?

**Comment by mouse9** [comment]
Yeah sure.
I understand I was just waiting for your reply first.

I will add test cases now

**Comment by mouse9** [comment]
@Siemienik I have added the integration test case for the same :)

**Review by Siemienik — APPROVED** [review]

**Comment by xcybplx** [comment]
For anyone landing here from a search: the cause was in `lib/utils/iterate-stream.js`, which paused the stream around each `yield`. unzipper's entry stream keeps working while paused and emits `end` once its input is exhausted, so entries not yet delivered were dropped silently. The reader hit it through its own workaround — buffering an early worksheet to a temp file — and that write was the delay that lost the rest, including the sharedStrings it was waiting for. Timing-dependent, hence green on Linux and red on macOS/Windows.

**Comment by gameroman** [comment]
I'd recommend trying out one of theseforks

https://github.com/excel-js/exceljs

https://github.com/cjnoname/excelts

https://github.com/protobi/exceljs

You can also see a [comparison on npmx](https://npmx.dev/compare?packages=exceljs,@cj-tech-master/excelts,@excel.js/exceljs,@protobi/exceljs)

**Pull request merged**
