### PR TITLE
add comment support #529

### PR DESCRIPTION
**Pull request by ilimei**
Fixes issue #529

### CODE REVIEW

**Comment by guyonroche** [comment]
@ilimei thank you for your contribution - this looks good. Could you do one thing? Please use 2 spaces for indents  - I know it's pedantic but it helps with consistency

**Comment by ilimei** [comment]
@guyonroche sorry for that, i will do it later ^_^

**Comment by guyonroche** [comment]
@ilimei after some futher testing, I've started working on some changes...
1) changing the Cell property name from "comment" to "note" -> this reflects the change in Excel from comments to "Threaded Comments". The old legacy comments are called Notes
2) It turns out that each note (or comment) requires the addition of a vml drawing for each cell note. Sometimes the design decisions of MS Excel developers astounds me!

**Comment by guyonroche** [comment]
Changes are in and published to 1.12.0
@ilimei thanks for your contribution

**Comment by alexcrack** [comment]
Hello.
1. Comment's names in the interface file *.d.ts (and in @types/exceljs module) called 'comment' (not 'note') as before.
2. Comments are not popupable. They are displayed constantly. But Excel (and Libre Calc) CAN do them popup on cell hover.

Can't you check it please?

**Pull request merged**
