### PR TITLE
Feat: Migration from moment to dayjs

### PR DESCRIPTION
**Pull request by ben33**
Hi,
Since I try to shrink the packages of my apps and I've seen the issue  #794,
I've done the migration from moment to dayjs
Feel free to ask me anything because I'm not sure how to do it the right way for you ( i did not build and push build lib for example)

Thanks for your lib !

### CODE REVIEW

**Comment by A1rPun** [comment]
I can't wait for this PR to merge! The commit looks fine (`dayjs` api is the same as `moment`) :+1:

**Comment by alubbe** [comment]
Okay the tests are not green on travis - @ben33 could you take a look? https://travis-ci.org/exceljs/exceljs/builds/572796131

**Comment by ben33** [comment]
I take a look, did not do anything and it's green XD
Any other thing ? XD

**Comment by alubbe** [comment]
Looks good to me!

**Pull request merged**
