### PR TITLE
fix: styles rendering in case when "numFmt" is present in conditional formatting rules (resolves #1814)

### LINKED ISSUE #1814: [BUG] Adding "numFmt" to conditional formatting rule corrupts document
## 🐛 Bug Report

After specifying `numFmt` pattern as a style for conditional formatting rule, MS Excel states a problem during opening generated file. The issue is reproducible for both basic and streaming APIs. 

issue

Lib version: 4.2.1
MS Excel version: 16.52
OS: MacOS Big Sur (11.4)

## Steps To Reproduce

For issue reproduction, next snippet is suggested (run it and try to open generated file):

```javascript
const Excel = require('exceljs');

const { WorkbookWriter } = Excel.stream.xlsx;

(async () => {
    const workbook = new WorkbookWriter({ filename: 'test.xlsx', useStyles: true });
    const worksheet = workbook.addWorksheet('example');

    worksheet.addConditionalFormatting({
        ref: 'A1:A2',
        rules: [{
            type: 'cellIs',
            operator: 'between',
            formulae: [0, 10],
            style: { numFmt: '0.00' },
            priority: 1,
        }],
    });

    [5.5, 15.5].forEach((value, index) => {
        const row = worksheet.getRow(index + 1);
        const cell = row.getCell(1);
        cell.value = value;
        row.commit();
    });

    worksheet.commit();
    await workbook.commit();
})();
```

## Expected Behavior

The file should be generated validly and it should contain specified conditional formatting rules.

## Investigation Notes

The issue is described by an invalid `numFmt` tag inside `styles.xml`:

```xml
<dxfs count="1">
        <dxf>
            <numFmt/>
        </dxf>
</dxfs>
```

While valid markup should look like:
```xml
<dxfs count="1">
        <dxf>
             <numFmt numFmtId="number" formatCode="0.00"/>
        </dxf>
</dxfs>
```

### PR DESCRIPTION
**Pull request by andreykrupskii**
## Summary

Closes #1814

This code covers fix for https://github.com/exceljs/exceljs/issues/1814. The issue is described by `numFmt` tag is rendered without `numFmtId` and `formatCode` properties when it is located in `dxf` tag (that is used for dynamic styles, for example, conditional formatting). This specific case is handled by the changes in the scope of this pull request.

## Test plan

The next code snippet is suggested for testing:
```javascript
const Excel = require('./excel');

const { WorkbookWriter } = Excel.stream.xlsx;

(async () => {
    const workbook = new WorkbookWriter({ filename: 'test.xlsx', useStyles: true });
    const worksheet = workbook.addWorksheet('example');

    const column = worksheet.getColumn(1);
    column.style.numFmt = '0.0#';

    worksheet.addConditionalFormatting({
        ref: 'A:A',
        rules: [{
            type: 'cellIs',
            operator: 'greaterThan',
            formulae: [1000],
            style: { numFmt: '0.0#,K' },
            priority: 1,
        }],
    });

    [100.5, 1000.5].forEach((value, index) => {
        const row = worksheet.getRow(index + 1);
        const cell = row.getCell(1);
        cell.value = value;
        row.commit();
    });

    worksheet.commit();
    await workbook.commit();
})();

```

Script execution result **before fix apply**:

corrupted-file
corrupted-xml

Script execution result **after fix apply**:

valid-file
valid-xml

## Related to source code (for typings update)

Typings update is not required.

### CODE REVIEW

**Comment by andreykrupskii** [comment]
@alubbe, @Siemienik, @Alanscut, I kindly ask you to review this pull request.

**Review by Schdoop — APPROVED** [review]

**Comment by alubbe** [comment]
thanks, this is a great PR! Could you please add a unit test for the xml generation?

**Comment by andreykrupskii** [comment]
@alubbe, sure, I will add tests

**Comment by andreykrupskii** [comment]
@alubbe, I covered this case with an integration test, thanks

@alubbe, @Siemienik, @Alanscut, I kindly ask you to review and merge it.

**Review by Siemienik — APPROVED** [review]
LGTM 🥇  Thank you for that contribution ;)

**Comment by andreykrupskii** [comment]
@Siemienik, I double-checked tests locally and they passed, while I also was able to reproduce the problem when the pipeline got stuck due to `test:jasmine` script (looks like `grunt-contrib-jasmine` does not receive response from headless browser during setup). Please, advise, how can we proceed with this pull request?

**Comment by andreykrupskii** [comment]
@alubbe, @Siemienik,  @guyonroche, please, take a look at my previous comment and, please, advise.

**Comment by andreykrupskii** [comment]
@Siemienik, @alubbe, @guyonroche, please, review one more time 😉

I've added a fix that prevents `test:jasmine` job from getting stuck - https://github.com/exceljs/exceljs/pull/1815/files#diff-e22a0e4b362f0115dd0b86fb682098a5eedfa816971c4c7932b8e8e106d3946dR125

The issue with stucking pipeline is described by `grunt-contrib-jasmine` library that embeds `jasmine` library inside and has an issue with running tests using the latest `jasmine` version. More info can be found via https://github.com/gruntjs/grunt-contrib-jasmine/issues/339.

I've tested pipeline execution using my fork and it successfully passed - https://github.com/andreykrupskii/exceljs/pull/2

Feel free to ask any questions/suggestions and I look forward to the merge of this PR.

**Review by alubbe — APPROVED** [review]

**Comment by alubbe** [comment]
Thanks for this PR and unblocking jasmine!

**Comment by harunisik** [comment]
This issue is still happening in the latest version 4.3.0.

**Comment by andreykrupskii** [comment]
Hi there @harunisik! I was just looking at the changes and I didn't see the latest update published. I noticed that V4.3.0 was published on Aug 21, 2021, and this change was merged on Sep 7, 2021. Hey @alubbe, do you happen to know the current status of this project and if it has active maintainers? Thanks so much!

**Comment by Siemienik** [comment]
Hi, no one except Guyonroche has permission to publish package. Recently I publish it from fork https://github.com/SiemaTeam/spreadsheets .
Could you try if is it working properly from that fork?

btw. we're organizing MergeFest to cleanup current PRs list, they are on Discord https://discord.gg/siema .

**Comment by RPE8** [comment]
> Hi, no one except Guyonroche has permission to publish package. Recently I publish it from fork https://github.com/SiemaTeam/spreadsheets . Could you try if is it working properly from that fork?
> 
> btw. we're organizing MergeFest to cleanup current PRs list, they are on Discord https://discord.gg/siema .

I tried it today - so far so good. Thanks.

**Pull request merged**
