### PR TITLE
Fix Issue #73 #226 #664 #366 #638

### PR DESCRIPTION
**Pull request by LesterLyu**
### Fix bugs:
 - Cannot read worksheet.state properly https://github.com/guyonroche/exceljs/issues/73 https://github.com/guyonroche/exceljs/issues/226
 - Defined name malfunctioning https://github.com/guyonroche/exceljs/issues/664
 - Defined name malfunctioning when name contains ```'```

#### Test case added for checking worksheet.state.

### CODE REVIEW

**Comment by LesterLyu** [comment]
@guyonroche Travis-ci says ```sh: 1: nsp: not found```, might because nsp is deprecated.

**Comment by LesterLyu** [comment]
### Fix hyperlink
Since hyperlink should be able to apply to any cell type, hyperlink should not be a type: ```Excel.ValueType.Hyperlink``` is removed.
### How to set hyperlink?
Internal & external hyperlinks are supported, however, **Stream I/O does not support hyperlinks**.
You can add hyperlink to any cell types:

E.g.

```javascript
worksheet.getCell('A1').value = 'Hello World';
// Set internal hyperlink, link to Sheet2!A1
worksheet.getCell('A1').hyperlink = { mode: 'internal', target: 'Sheet2!A1' };

worksheet.getCell('A2').value = { formula: 'A1+A3', result: 7 };
// Set External hyperlink, link to 'https://google.com'
worksheet.getCell('A1').hyperlink = { mode: 'external', target: 'https://www.google.com' };
```

**Comment by pmukherjeee** [comment]
@guyonroche can this be merged?

**Comment by Siemienik** [comment]
Hello @LesterLyu i will invite You to pull this request here: https://github.com/p3rio/exceljs, 
I going to maintain this library there.
Regards

**Comment by Siemienik** [comment]
@LesterLyu thank you, fingers crossed :)

**Comment by lawrencehook** [comment]
@LesterLyu Has your fix for hyperlinks been merged yet? I'm trying to create a hyperlink in a cell that has a Number type. Seems like hyperlinks still only work for text cells.

**Pull request closed without merging**
