### PR TITLE
fix(image): fix editAs assignment

### PR DESCRIPTION
**Pull request by mbenzenhoefer**
Fixes issue #680

### CODE REVIEW

**Comment by Siemienik** [comment]
@mbenzenhoefer it looks fine, could I please you to write any test that checks this bug is resolved?

**Comment by guyonroche** [comment]
@mbenzenhoefer I've just merged another PR that worked in this area and published to NPM. Can you confirm whether the latest version fixes your issue?
Thanks,
Guyon

**Comment by Siemienik** [comment]
does anyone know how to resolve this conflict?

**Comment by guyonroche** [comment]
@Siemienik fixing the conflicts will be fairly easy - the main question is whether this PR is still relevant after the recent changes that have been merged in

**Comment by alubbe** [comment]
@mbenzenhoefer could you check whether the issue persists with the other recent fix?

**Pull request merged**
