### PR TITLE
Wait for writing to tmp fiels before handling zip stream close

### PR DESCRIPTION
**Pull request by sohai**
I'm having a hard time to write a failing test without those changes but in one commercial project, we have tests that were flaky without this.

### CODE REVIEW

**Comment by sohai** [comment]
I moved resolving promise to finish listener of tempStream to handle a rare case when zip close event occurs before `entry.pipe(tempStream);` finish

**Comment by alubbe** [comment]
@Siemienik @guyonroche I think we should merge this, but I'm not sure if we can write a test here. What do you think?

**Comment by Siemienik** [comment]
This is not a perfect practice to commit something without tests. 

mhmm... could you test emitting error?  (Do you know any situation that should throw an exception?)

**Comment by alubbe** [comment]
Maybe we could use proxyquire? I think the failure is actually really unlikely, the issue is actually around the first tmp callback potentially getting called AFTER the finished event has already been triggered, so `this.waitingWorkSheets` is empty even though it should have content

**Comment by sohai** [comment]
@Siemienik I added one test. I totally understand that this is not good practice to commit something without tests but as I mentioned I could not figurated out how to do that properly, please let me know if you have some better ideas to test it.

**Pull request merged**
