### PR TITLE
chore: upgrade jszip to ^3.10.1

### PR DESCRIPTION
**Pull request by jarrod-cocoon**
## Summary

This patches the zipslip vulnerability in <= 3.7.1 and patched in >= 3.8.0.

No issues found with our usage in https://stuk.github.io/jszip/CHANGES.html, most notable change was 3.9.0 API change, but we are unaffected, due to not using constructor arguments.

## Test plan

Run npm install and npm test after upgrading. All tests passed.

### CODE REVIEW

**Comment by GBPROB2** [comment]
+1

**Comment by jarrod-cocoon** [comment]
Hi @Alanscut, @alubbe or @Siemienik, and sorry to bother y'all.  Whats the best way to get a review here?

**Comment by Siemienik** [comment]
Hi @jarrod-cocoon, as I have got a little bit more free time recently, I'm going to review most part of the PRs. Thank you for your contribution :)

Apart from the review, I organize a contributor community on Discord, where regularly we meet on `MergeFest` to talk about the future of this project and some others. 
This PR I reviewed during one of these MergeFests :) If would you like to join us: https://discord.gg/siema

**Review by Siemienik — APPROVED** [review]
LGTM

**Pull request merged**
