### PR TITLE
Image positioning fix

### PR DESCRIPTION
**Pull request by kaidoj**
This is a fix as discussed https://github.com/guyonroche/exceljs/issues/467
As the original fix author https://github.com/Trynex did not create pull request then i will.
I did test it and this fixed my issue.

### CODE REVIEW

**Comment by nezaidu** [comment]
you're the man!

**Comment by Siemienik** [comment]
@nezaidu  i fix it in pull request #702, 
if You need it quicly, i have build branch in my repo: 
https://github.com/p3rio/exceljs/tree/build

npm:
```
    "dependencies": {
        "exceljs": "github:p3rio/exceljs#build"
    }
```

**Comment by alubbe** [comment]
@kaidoj so the only change is here, right? https://github.com/exceljs/exceljs/pull/691/files#diff-36f4b57761a8f069733aa289ffdcb1c3

could you remove all the noise from this PR and extract a test case? Or close the PR if this is no longer relevant?

**Comment by kaidoj** [comment]
Closing this. This works for me atm. I have no time to test the alternative https://github.com/exceljs/exceljs/pull/702. If @Siemieniks PR works and is fine, then merge that.

**Pull request closed without merging**
