### PR TITLE
Updated documentation: Fixed exceljs object name

### PR DESCRIPTION
**Pull request by Subhajitdas298**
## Summary

Fixed exceljs object in documentation

## Test plan

No test needed.

### CODE REVIEW

**Comment by Subhajitdas298** [comment]
@guyonroche Some tests are not passing due to dependency issue (404) in MacOS tests. This is a small change for documentation fix.
Please review, and if ok and if possible, please consider a new minor version, with earlier changes as well. Thank you.

**Comment by Subhajitdas298** [comment]
MacOS timeout issue in an old test case, possibly due to macos environment issue mentioned by other people

**Comment by Subhajitdas298** [comment]
@guyonroche MacOS tests are much slower (3m 53s) as opposed to 1m 5s in ubuntu test and 1m 29s in windows tests. It is possible due to recent macos-latest buggy release [`macos-latest` very slow `actions/cache@v1`](https://github.community/t/macos-latest-very-slow-actions-cache-v1/18282), [Apple builds suddenly super slow internet connection #657](https://github.com/actions/virtual-environments/issues/657) etc. Can you please increase the timeout of macos tests (by 3 times, as it is taking around thrice the time)?

**Comment by Subhajitdas298** [comment]
> @guyonroche MacOS tests are much slower (3m 53s) as opposed to 1m 5s in ubuntu test and 1m 29s in windows tests. It is possible due to recent macos-latest buggy release [`macos-latest` very slow `actions/cache@v1`](https://github.community/t/macos-latest-very-slow-actions-cache-v1/18282), [Apple builds suddenly super slow internet connection #657](https://github.com/actions/virtual-environments/issues/657) etc. Can you please increase the timeout of macos tests (by 2.5 times, as it is taking around thrice the time)?

The issue seems to be fixed.

**Review by alubbe — APPROVED** [review]
thanks!

**Pull request merged**
