### PR TITLE
inlineStr cell type support #1575

### PR DESCRIPTION
**Pull request by drdmitry**
## Summary

Implementing inlineStr cell type fixing issue #1575

## Test plan

Tested stream reading of the xlsx file that has cells defined as `<c ... t="inlineStr"><is><t>value here</t></is></c>` - values gets populated, instead of null values before the fix.

### CODE REVIEW

**Comment by alubbe** [comment]
Could you please add a new test with that test file to make sure we don't lose this functionality over time?

**Comment by drdmitry** [comment]
@alubbe, added integration test with the sample file.

**Comment by drdmitry** [comment]
@Siemienik, could you please review and merge this PR?

**Comment by Siemienik** [comment]
Yes, I will if only I found free time.

**Review by alubbe — APPROVED** [review]

**Comment by sveisvei** [comment]
When will this be released?

**Comment by gaurav-cointab** [comment]
when will this be release, because right now in "4.3.0" also this fix is not present. We are getting the inlineStr cell as "NULL", please make a small release for this issue, if possible... Currently we are using the npm release version. Do we have to pull from github directly and then use the fix, or will you be making a release in npm also ?

**Comment by adrian-morariu-clarisoft** [comment]
@Siemienik please release a new version with this fix

**Comment by Siemienik** [comment]
@adrian-morariu-modus-create see #2351 ,

**Pull request merged**
