### PR TITLE
Fix: Sheet Properties Types

### PR DESCRIPTION
**Pull request by albeniraouf**
## Related to source code (for typings update)
https://github.com/exceljs/exceljs/blob/eec76a1d4e01e634d2fd9b3d2030cd36a0f2add4/spec/unit/xlsx/xform/sheet/sheet-properties-xform.spec.js#L43
https://github.com/exceljs/exceljs/blob/eec76a1d4e01e634d2fd9b3d2030cd36a0f2add4/lib/stream/xlsx/worksheet-writer.js#L532
https://github.com/exceljs/exceljs/blob/eec76a1d4e01e634d2fd9b3d2030cd36a0f2add4/lib/xlsx/xform/sheet/worksheet-xform.js#L302

### CODE REVIEW

**Comment by albeniraouf** [comment]
@Siemienik  please consider reviewing the PR and release ASAP as it breaks our code and requires using "any" type which is not correct

**Comment by zurmokeeper** [comment]
@albeniraouf Could you please move [over here](https://github.com/zurmokeeper/excelize)? I'd be happy to merge this feature.

**Comment by Siemienik** [comment]
@zurmokeeper I really want to appreciate your thoughts into Open Source Software development, just also I would like to notice that you remove the commit log with info who's author of code on your "fork". Please consider that it's not probably the nicest way to continue development.

**Comment by Siemienik** [comment]
Thank you @albeniraouf. that's good patch 👍

**Pull request merged**
