### PR TITLE
add cn doc

### PR DESCRIPTION
**Pull request by loverto**

### CODE REVIEW

**Comment by guyonroche** [comment]
@loverto This looks cool.
How is this file generated?
The readme file does change now and then - new features, version history, etc. so it's likely that this translation will get out of date. Would it be worth adding a "Correct as of v1.12.0" stamp at the top?
Also - if we can't update it on every release, it might be worth removing the "New Features" section

**Comment by loverto** [comment]
This file is translated by me. I can keep this file during the update. Of course, you add the version. I will add it later.

**Comment by JixunMoe** [comment]
> This file is translated by me. I can keep this file during the update. Of course, you add the version. I will add it later.

I don't believe you translated this document yourself, the use of machine translation is quite obvious.

---

> 即使只有失败测试的公关也很好 

PR (Pull Request) ≠ 公关 (Public Relations)

---

> 冰冻视图

This one is actually OK, but there's a word for this in Chinese. Please consult the official documentation for terminologies.

[冻结窗格](https://support.office.com/zh-cn/article/%E5%9C%A8-excel-for-mac-%E4%B8%AD%E5%86%BB%E7%BB%93%E7%AA%97%E6%A0%BC%E4%BB%A5%E9%94%81%E5%AE%9A%E9%A6%96%E8%A1%8C%E6%88%96%E9%A6%96%E5%88%97-b8eb717e-9d3e-4354-8c02-d779a4b404b2)

---

> 要冻结的列数。要仅冻结行，请将其设置为 0 或未定义

“未定义” 应该是保留字 [undefined](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined)，不用翻译

"未定义" should be the reserved identifier `undefined` and not be translated.

---

> Promises returned from functions switched from Bluebird to native node Promise which can break calling code if they rely on Bluebird's extra features.

> 从 Bluebird 切换到本机节点 Promise 的函数返回 Promise，如果它们依赖 Bluebird 的额外功能，它可以破坏调用代码。

A better example would be:

函数返回的 Promise 对象由 Bluebird 实现更换为原生 Promise 实现。如果调用方依赖 Bluebird 的某些特性则可能会出错。

---

> 首先，通过 addImage（）函数将图像添加到工作簿，该函数也将返回 imageId 值。
> ...
> 请注意，用于此的坐标系统为零，因此 A1 的左上角将为 {col：0，row：0}。 可以通过使用浮点数来指定单元的分数，例如， A1 的中点是 {col：0.5，row：0.5}。
> ...
> CSV 解析器使用 [fast-csv]（https://www.npmjs.com/package/fast-csv）编写 CSV 文件。 

很明显的代码片段中滥用全角符号，连 Markdown 里的链接括号都被你转换了。

The use of full-width characters. Quite common when you throw the whole paragraph (if not the whole document) to the translator.

---

My suggestions:

* Label the link to Chinese documentation with "Help needed to improve the translation quality" or similar text.
* Get someone to actually proofread the document instead of blindly merging it.
* Use `inline-monospace` tag in the English document for keywords e.g. `undefined` and `0` (values can be copied to use).

**Comment by wang1212** [comment]
I think the translation is pretty bad!!!

**Comment by wang1212** [comment]
I think the translation is pretty bad!!! Of course, I hope I can take the time to improve it myself.

**Pull request merged**
