### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by Siemienik**
We have a lot of bugs reported which has a poor description, it does not help us to reproduce and fix it quickly.
So I think the issue template should improve the situation :)

### CODE REVIEW

**Comment by alubbe** [comment]
I think that's a great idea, but I believe it needs to be short - otherwise users might end up ignoring it. Personally, I like https://raw.githubusercontent.com/facebook/jest/master/.github/ISSUE_TEMPLATE/bug.md so I've shortened our template to be similar to that. What do you think?

Also pinging @guyonroche

**Comment by Alanscut** [comment]
why not also add a PR template ?😃

**Comment by Siemienik** [comment]
@Alanscut yeach it;s great idea:)

**Comment by Siemienik** [comment]
@alubbe for me the important thing is to give me a test which will fail before fixation. We have a lot of bugs reported, that we need a lot of time to inspect and analyze them.

Test code for an issue will give us:

set the quality of issues to the highest level
reduce the fixation time cost
encourage to creating new PRs (if someone makes a test it will probably make a fixation :) )
In other side, You have right, the short template should increase bug reports amount.
So I have shared my thoughts with you, and I'm really open to change my vision to something else. 

@alubbe @Alanscut what do you think?

**Comment by alubbe** [comment]
I completely agree, that's why I tried to find a 'middle-ground' approach, that both looks short, so that it actually gets read instead of deleted, but still wants a code example. That's not as much as a fully blown test case, but it's close enough. Here's my suggestion:
```
## Steps To Reproduce

<!-- The exact steps required to reproduce the issue, ideally with a code example and an expectation (like in a unit test) -->

```javascript
const wb = new ExcelJS.Workbook();
const ws = wb.addWorksheet('XYZ');
ws.getCell('A1').value = 7;
expect(ws.getCell('A1').value).to.equal(7);
```

**Comment by alubbe** [comment]
@Alanscut this PR adds more templates: https://github.com/exceljs/exceljs/pull/1128

**Pull request merged**
