### PR TITLE
Support setting margins from cell comments

### PR DESCRIPTION
**Pull request by Alanscut**
## Changes

1. The purpose of this PR is to support setting margins for cell comments.
2. Please let me know if this PR needs anything else.

### CODE REVIEW

**Comment by Alanscut** [comment]
hi @guyonroche @Siemienik @alubbe , I sent you a email, if possible, I hope to be the maintainer of exceljs, looking forward to your reply and guidance, thanks!

**Comment by Siemienik** [comment]
@Alanscut why did you close PR?

**Comment by Alanscut** [comment]
this PR is not complete, #1159 has replaced it.

**Comment by Siemienik** [comment]
@Alanscut thanks

**Pull request closed without merging**
